In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv("kegg_w_cate_split.csv",index_col=0)
data

    Approved    KEGG                 Ingredient     id1  id2  id3  id4
0       1983  D04269                  Soysterol     NaN  NaN  NaN  NaN
1       1983  D01612         Sodium picosulfate  2359.0  NaN  NaN  NaN
2       1984  D08751   Semi-alkaline proteinase     NaN  NaN  NaN  NaN
3       1985  D01585                  Exalamide     NaN  NaN  NaN  NaN
4       1985  D01506       Dimemorfan phosphate  2229.0  NaN  NaN  NaN
..       ...     ...                        ...     ...  ...  ...  ...
93      2020  D01357     Betamethasone valerate  2646.0  NaN  NaN  NaN
94      2021  D01007  Propiverine hydrochloride  2590.0  NaN  NaN  NaN
95      2021  D00118                   Naproxen  1149.0  NaN  NaN  NaN
96      2021  D02729     Itopride hydrochloride  2399.0  NaN  NaN  NaN
97      2022  D03306      Calcium polycarbophil  2399.0  NaN  NaN  NaN

[98 rows x 7 columns]

In [2]:
data_3=data.copy()
data_2=data.copy()
for i,ids in enumerate(data["id1"]):
    for j in range(4):
        column_name =f"id{j+1}"
        if not pd.isnull(data.loc[i,column_name]):
            data_3.loc[i,column_name]=str(data.loc[i,column_name])[:3]
            data_2.loc[i,column_name]=str(data.loc[i,column_name])[:2]

In [3]:
#melt 
data_3=data_3.melt(id_vars=["Approved","KEGG","Ingredient"],value_name="id")
data_2=data_2.melt(id_vars=["Approved","KEGG","Ingredient"],value_name="id")
data_3=data_3[data_3["id"].notna()].reset_index(drop=1)
data_2=data_2[data_2["id"].notna()].reset_index(drop=1)

In [4]:
data_3.to_csv("ingre_cate_len3.csv")
data_3

     Approved    KEGG                   Ingredient variable   id
0        1983  D01612           Sodium picosulfate      id1  235
1        1985  D01506         Dimemorfan phosphate      id1  222
2        1985  D00141                  Indometacin      id1  114
3        1985  D00126                    Ibuprofen      id1  114
4        1986  D04267  Polyenephosphatidyl choline      id1  218
..        ...     ...                          ...      ...  ...
109      2009  D00904            Diclofenac sodium      id3  264
110      2010  D00689   Beclometasone dipropionate      id3  245
111      2011  D00282                 Clotrimazole      id3  629
112      1997  D00526          Sodium cromoglicate      id4  449
113      2006  D00983      Triamcinolone acetonide      id4  264

[114 rows x 5 columns]

In [5]:
data_2.to_csv("ingre_cate_len2.csv")
data_2

     Approved    KEGG                   Ingredient variable  id
0        1983  D01612           Sodium picosulfate      id1  23
1        1985  D01506         Dimemorfan phosphate      id1  22
2        1985  D00141                  Indometacin      id1  11
3        1985  D00126                    Ibuprofen      id1  11
4        1986  D04267  Polyenephosphatidyl choline      id1  21
..        ...     ...                          ...      ...  ..
109      2009  D00904            Diclofenac sodium      id3  26
110      2010  D00689   Beclometasone dipropionate      id3  24
111      2011  D00282                 Clotrimazole      id3  62
112      1997  D00526          Sodium cromoglicate      id4  44
113      2006  D00983      Triamcinolone acetonide      id4  26

[114 rows x 5 columns]